### ISSUE TITLE
Fallo en la documentación del CORDIC

### ISSUE THREAD

**Issue by PabloGonzalezSegarra** [HyperloopUPV-H8/ST-LIB#108]
### Problema:

A todos los comentarios doxygen del CORDIC les falta un asterisco al principio.

![image](https://user-images.githubusercontent.com/58437819/207718061-5d8a2316-f88c-487e-890d-9af7852fbac4.png)

### Solución:

![image](https://user-images.githubusercontent.com/58437819/207718007-f99471b5-8eab-4f76-ad0c-b4692900c50e.png)

**Comment by alejandrogonzalvo** [comment]
In PR

**Comment by alejandrogonzalvo** [comment]
literally 20 seconds

**Comment by ricardochust** [comment]
pull request to solve this already accepted.
Issue closed
