### ISSUE TITLE
DigitalInput XOR ADC

### ISSUE THREAD

**Issue by ricardochust** [HyperloopUPV-H8/ST-LIB#134]
Parece que hay un problema con el ADC::start(), cuando se usa parece pisar una parte de la inicializacion del Pin::start(), lo cual provoca que el DigitalInput deje de funcionar. 

Aqui el ejemplo de la prueba, un codigo muy simple:

```cpp
/* USER CODE BEGIN 1 */
Pin& myPin = PA3;
Pin& myPin2 = PC0;
uint8_t id = DigitalInput::inscribe(myPin);
uint8_t id2 = ADC::inscribe(myPin2).value();

 /* Initialize all configured peripherals */
  Pin::start();
  MX_DMA_Init();
  ADC::start();
  MX_LPTIM1_Init();
  MX_LPTIM2_Init();
  MX_LPTIM3_Init();

/* USER CODE BEGIN 2 */
  ADC::turn_on(id2);

/* USER CODE BEGIN 3 */
value = DigitalInput::read_pin_state(id).value();
value2 = ADC::get_value(id2).value_or(-1);
HAL_Delay(100);
```

Si descomentas el ADC::start(); el ADC funciona y el Digital no. Si lo comentas el ADC deja de funcionar (obviamente) y el Digital comienza a funcionar. Si cambias el orden de ambos Digital va y ADC no, osea que se pisan mutuamente. 

----------
Parece que el ADC::start() es condicion necesaria pero no suficiente para provocar el error. Tambien es necesario inscribir un pin en el ADC para que suceda. Si se comenta la inscripcion del ADC puede estar el ADC::start() despues del Pin::start() y sigue funcionando el DigitalInput (pero no tienes ningun adc). 
De hecho, parece que a veces antes de dejar de funcionar hace 1 lectura funcional. Luego deja de leer correctamente. 

El PC0 como ADC esta funcionando pero dentro del pinVector (en el caso en el que no funciona el Digital) esta configurado como not_used en lugar de analog (y sigue funcionando).

**Comment by ricardochust** [comment]
De los ADC van:
PC0, PA3, PA4, PA5, PA0, PB0, PA6, PF11, PF12, PF13, PF14, 

No van:
PC2, PC3, PF5, PF6, PF7, PF8 (todos los del ADC3)

**Comment by alejandrogonzalvo** [comment]
Solucionado
