### ISSUE TITLE
Añadir int functions para el ADC

### ISSUE THREAD

**Issue by ricardochust** [HyperloopUPV-H8/ST-LIB#139]
La lectura del adc transforma el valor uint a float, que es lo necesario para la mayoria de los casos
Pero la libreria math usa matematicas de int, por lo que no tiene sentido castear a float para volver a castear a int. Si queremos usar la libreria math con valores leidos deberiamos tener la opcion de leer el ADC sin recastearlo. 

**Aviso: el ADC3 debera ser shifteado 4 bits a la derecha para tener la misma escala que el ADC2 y el ADC1.** (quizas seria de interes que pudiese recibir de parametro el shift para decidir la escala, aparte y despues del shift de 4)

**Comment by StefanCostea** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Añadir metodo a los ADCs](https://trello.com/c/P7acDVv9/88-a%C3%B1adir-metodo-a-los-adcs)
