### ISSUE TITLE
Modularizar Mapas PIN -> PERIFERICO

### ISSUE THREAD

**Issue by alejandrogonzalvo** [HyperloopUPV-H8/ST-LIB#14]
Actualmente los servicios que utilizan pines tienen un mapa en el cpp con los PINES disponibles que se crea a partir del ioc. Creo que sería mejor meter todos esos mapas en un archivo a parte y utilizar un extern en el cpp en cuestion:

pros:
- cpp más limpio.
- Modularizar configuraciones. (si se quiere otra configuracion, se crea otro archivo a parte, no se edita el servicio directamente).
- Seria mucho más fácil implementar un generador de un archivo runes.hpp a partir de un IOC.

contras:
- no veo

posibles features:
- typedef para los mapas, mucho más limpio leer PinADCmap, que map<Pin, ADCchannel>.
- Ponedme todas las abstracciones y cosas chulas que le pondríais al runes.hpp porfa.

**Comment by PabloGonzalezSegarra** [comment]
Me parece una muy buena idea. Este lunes lo hablamos.

**Comment by alejandrogonzalvo** [comment]
Esta hecho y en pull request
