### ISSUE TITLE
Bugs Time class

### ISSUE THREAD

**Issue by ricardochust** [HyperloopUPV-H8/ST-LIB#145]
### Time::set_time_out no parece eliminar correctamente el low_precission_alarm que usa despues de activarse una vez

Codigo:

```cpp
	Time::register_low_precision_alarm(1000,[&](){A++;});
	Time::set_timeout(3000,[&](){A = 10;});
```

Resultado esperado: cada segundo aumenta 1, y en el segundo 3 lo pone a 10. En el segundo 7 deberia ser 14
Resultado dado: cada segundo aumenta 1, y cada 3 segundos lo pone a 10. En el segundo 7 es 11

### Time::register_high_precision_alarm ejecuta la funcion dada como parametro dos veces al ser convocada, mientras que Time::register_low_precision_alarm no. 

Codigo:

```cpp
	Time::register_low_precision_alarm(1000,[&](){A++;});
	Time::register_high_precision_alarm(1100000,[&](){A--;});
```

Resultado esperado: nunca deberia llegar a hacer underflow, pues high_precision alarm se registro despues y sucede cada 1.1 segundos en lugar de 1 segundos. 
Resultado dado: register_high_precision_alarm activa dos veces la funcion lambda que recibe, poniendo la variable uint64_t A a 18,446,744,073,709,551,614. El programa tarda aproximadamente 11 segundos en hacer overflow a 0 y 20 segundos en quedarse "por encima" del 0 de forma estable (como el desfase es de 0.1/1 segundo deberia tardar 10 segundos en progresar 1 el valor de A, si tarda 20 segundos en ponerlo de forma estable por encima de 0 es que aplico dos veces el -2. Ademas, el valor inicial dado cuadra con un underflow de 2 a un uint64_t)

Otro ejemplo
Codigo:

```cpp
	uint8_t tid = Time::register_low_precision_alarm(1000,[&](){A++;});
	Time::register_high_precision_alarm(1100000000,[&](){Time::unregister_low_precision_alarm(tid);});
```
Resultado esperado: el low_precision_alarm deja de contar al cabo de 1100 segundos, la primera vez que se activa la funcion de register_high_precision_alarm
Resultado dado: se activa la funcion nada mas es convocado el metodo y low_precision_alarm no suma a A ni una vez. Si se comenta la linea del high_precision_alarm cuenta perfectamente.

**Comment by StefanCostea** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Time Alarm](https://trello.com/c/goxGtQKi/89-fix-time-alarm)

**Comment by ricardochust** [comment]
![COM7 - PuTTY 01_02_2023 16_35_01](https://user-images.githubusercontent.com/116189892/216088351-f4ed2881-dbc1-436a-be4d-5d1b7d16e492.png)

Test de 25 minutos sobre cuantos decisegundos cuenta. El tiempo de ejecucion fue 1500+-1 segundos

**Comment by ricardochust** [comment]
![COM7 - PuTTY 01_02_2023 17_11_31](https://user-images.githubusercontent.com/116189892/216098662-9b0cabd4-3538-42ce-afc9-61fa45c1f337.png)
mismo test en 1 hora, 1 minuto y 30 segundos. El tiempo de ejecucion segun el movil fue 3690+-1 s.
