### ISSUE TITLE
Sensors are not included in  ST_LIB_LOW.hpp

### ISSUE THREAD

**Issue by StefanCostea** [HyperloopUPV-H8/ST-LIB#147]
Sensors are not included in  ST_LIB_LOW.hpp.

This should be fixed just by adding them.

**Comment by StefanCostea** [comment]
Also include paths on Sensors have to be updated, they still use the old convention

**Comment by ricardochust** [comment]
i made a pull request to solve this along with some other errors on the sensor class, close this issue so we move the topic to the pull request
