### ISSUE TITLE
A la clase DigitalOutput le falta una función toggle.

### ISSUE THREAD

**Issue by PabloGonzalezSegarra** [HyperloopUPV-H8/ST-LIB#151]
La clase `DigitalOutput` le falta una función toggle lo cual hace engorroso hacer parpadear leds. Ahora mismo para hacer parpadear un led hay que hacer: 

```cpp
if (toggle) {
		LED_CAN.turn_on();
		toggle = false;
	}else{
		LED_CAN.turn_off()
		toggle = true;
	}
```

Además la función `set_state()` es redundante porque ya puedes poner los dos estados con las funciones `turn_on()` y `turn_off()`.

Mi propuesta:
```cpp

class DigitalOutput {
public:
	DigitalOutput() = default;
	DigitalOutput(Pin& pin);

	void turn_on();
	void turn_off();
	void toggle();
private:
	uint8_t id;
	Pin pin;
};
```

**Comment by StefanCostea** [comment]
oido cocina

**Comment by StefanCostea** [comment]
aunque yo dejaria set state

**Comment by StefanCostea** [comment]
ya que te permite colocar el estado con una variable en runtime sin hacer comprobaciones de ifs y tal

**Comment by PabloGonzalezSegarra** [comment]
vale, se puede dejar el set_state pero el toggle vendria muy bien.

**Comment by ricardochust** [comment]
entonces eliminad turn_on y turn_off no? set_state ya hace lo que ambos pero mejor
o tiene alguna utilidad fuera del normal use case?

**Comment by PabloGonzalezSegarra** [comment]
A ver hay que dejar los que ya estan y añadir una más que sea toggle.
