### ISSUE TITLE
Iterar el mapa de available_instances no registra las PWM correctamente.

### ISSUE THREAD

**Issue by alejandrogonzalvo** [HyperloopUPV-H8/ST-LIB#216]
![image](https://user-images.githubusercontent.com/59616818/221838124-5bea5447-a7ad-4030-ae58-2163b2e96c57.png)

El pin PE14 funciona correctamente, el resto de pines registrados con el mapa no.

**Comment by StefanCostea** [comment]
Parece un problema de referencias. Mira a ver si algo por debajo recoge por referencia

**Comment by PabloGonzalezSegarra** [comment]
Este issue sigue activo?
