### ISSUE TITLE
How to link an external project with ST-LIB using linked folders.

### ISSUE THREAD

**Issue by alejandrogonzalvo** [HyperloopUPV-H8/ST-LIB#22]
### How to link an external project with ST-LIB using linked folders.
Linking projects with STM32 IDE can mess with relative includes pretty easy. Here is the solution I Found using linked folders.

A linked folder is basically a virtual folder that points to the route of a real one, kinda like pointers.
To create one, we go to the project explorer and click New->Folder. Then we configure it like this:
![image](https://user-images.githubusercontent.com/59616818/198547866-2310024c-a383-4494-99b2-252c28ba0721.png)

Now, we have our folder but we probably can't see it. This is because the project explorer automatically hides certain files. Go into filters and deactivate all options, except .* files:
![image](https://user-images.githubusercontent.com/59616818/198548776-dca7e4f1-ba38-4882-8918-3a135ca80a7d.png)
![image](https://user-images.githubusercontent.com/59616818/198548891-f0988034-5052-49ea-b02c-d6e665f9f5e9.png)

Now you should be able to see your linked folder:
![image](https://user-images.githubusercontent.com/59616818/198549045-a67bef40-484f-4db7-bd84-70aa7bd8fe14.png)

Next step, go to Project -> Properties and configure your include paths like this:
![image](https://user-images.githubusercontent.com/59616818/198549683-70e0f3db-960b-4d10-a6fc-e7bdf7d0e9e4.png)
![image](https://user-images.githubusercontent.com/59616818/198550018-049667f5-80d5-4cca-b0bc-dab83a4ba659.png)
![image](https://user-images.githubusercontent.com/59616818/198550102-033944d9-ce94-401d-872e-c3078be5ee6f.png)

### Common linking errors
![Captura de pantalla 2022-10-28 100523](https://user-images.githubusercontent.com/59616818/198550539-eee1e9ab-5ef8-48ac-b6c7-8907b7ec9281.png)
You haven't activated those ADC and TIM periferal in the ioc. So CUBEMX code generator hasn't generated the appropiate code for those classes. Just enable a timer and an ADC and put a channel to use. Then generate. Remember to change your file to main.c if you are working on a cpp project!

![Captura de pantalla 2022-10-28 100614](https://user-images.githubusercontent.com/59616818/198550969-968e4af2-9a9f-4d7c-8f16-dfd3ce492c31.png)
You are probably trying to compile main.c. Just change it to main.cpp.

![Captura de pantalla 2022-10-28 101512](https://user-images.githubusercontent.com/59616818/198551087-a47e0f99-ccd7-4471-9039-9e5aab989c01.png)
You probably have the ST-LIB project closed. Both the project and the library have to be open for this setup to work.

**Comment by PabloGonzalezSegarra** [comment]
No veo la necesidad de la carpeta virtual. Con añadir las siguientes carpetas en el proyecto ya funciona y queda más limpio.
![image](https://user-images.githubusercontent.com/58437819/198617822-f3176d41-6b9c-4817-a645-9da7d72810b6.png)

**Comment by PabloGonzalezSegarra** [comment]
El error en el que explicas que hay que añadir uno de cada periférico para que funcione se arregla descomentando en el proyecto que vamos a hacer la hal de todos los periféricos que vamos a tener en la ST-LIB. Como el proyecto base será el mismo esto tendremos que hacerlo solo una vez.

![image](https://user-images.githubusercontent.com/58437819/198672355-2a11a91f-01da-4cd5-895f-d2e74897f472.png)
Es el archivo stm32h7xx_hal_conf.h

**Comment by alejandrogonzalvo** [comment]
> No veo la necesidad de la carpeta virtual. Con añadir las siguientes carpetas en el proyecto ya funciona y queda más limpio. ![image](https://user-images.githubusercontent.com/58437819/198624185-3b0dd8a4-4236-4ba3-a2e2-4bb7e984445f.png)

Importante añadirlas tambien en el apartado assembly
