### ISSUE TITLE
DigitalInput name conflict

### ISSUE THREAD

**Issue by ricardochust** [HyperloopUPV-H8/ST-LIB#29]
I'm working on the DigitalInput ST-LIB_LOW class, but there is already another class called DigitalInput on the project. 
The HALAL's EXTI service class is named DigitalInput and so is its header, and my class uses the EXTI service too so i cannot simply not include it.
Should we change one of the classes names so there is no conflict or try to work around it both on the ST-LIB_LOW digitalInput class and the sensors class?
And which one should we change (if we do change them)? i would prefer to change the HALAL one for clarity but i m still writting the ST-LIB_LOW one so i could change mine without any issue. 

![image](https://user-images.githubusercontent.com/116189892/199456613-03c2652c-54c4-48c7-b7a6-ce3e9d09252c.png)

**Comment by StefanCostea** [comment]
Changed DigitalInput Sensor name to DigitalSensor
