### ISSUE TITLE
LinearSensor::read() not compiling

### ISSUE THREAD

**Issue by AmancioG** [HyperloopUPV-H8/ST-LIB#335]
When using LinearSensor::read() ST-LIB fails to compile with the following error message: 

`error: redeclaration of 'template<class Type> class LinearSensor' with different constraints`

**Comment by g0nz4I0** [comment]
Check screenshot


![image](https://github.com/HyperloopUPV-H8/ST-LIB/assets/58850783/6f0be113-a773-4358-be4c-43fb865c352e)
https://godbolt.org/z/Gse7PKWWz
