### ISSUE TITLE
Multiconnection server doesn t close listener socket on close all

### ISSUE THREAD

**Issue by ricardochust** [HyperloopUPV-H8/ST-LIB#337]
When a connection is closed and fault is entered the server doesn t properly close the listener socket, leading to one connection being available for a new client to connect. 

(This issue is a warning for anyone using Multiconnection, until I solve the issue)

**Comment by g0nz4I0** [comment]
I'm not sure its actually multiconnection, a single disconnect and then reconnect works also, although one could think of it as a multiconneciton 🤔
