### ISSUE TITLE
sntp declaration methods are commented

### ISSUE THREAD

**Issue by ricardochust** [HyperloopUPV-H8/ST-LIB#355]
As i remember, they were commented as they gave compilation errors, is that right?

If there is another reason why is it commented put it in here, otherwise i will make tests to make it not give compile errors and work properly. 

Also if it gave compilation errors with an specific set up tell me as i will make a few dummy tests with some modules that i think may give trouble otherwise.

**Comment by g0nz4I0** [comment]
Updating on this:

- SNTP methods are commented

After uncommenting on develop:
- SNTP takes 30 secs to update the value from the SNTP server


Steps to reproduce:

- Open a local SNTP server: here is a useful guide: https://ubuntuforums.org/showthread.php?t=862620
- Set a breakpoint on set_time function in ST-LIB/HALAL/Services/Communication/SNTP/SNTP.cpp

If you check the time it takes from SNTP::update() to this function is around 30 secs, this should be fixed. 


This links give some information: 

1. https://stackoverflow.com/questions/61932743/how-does-the-sntp-app-of-the-lwip-component-set-the-time-it-receives
2. https://www.nongnu.org/lwip/2_0_x/group__sntp.html

Once the time is received via SNTP, RTC takes over.

Also SNTP methods should be renamed to something more descriptive
