### ISSUE TITLE
development SPI is not working, FIX ASAP

### ISSUE THREAD

**Issue by g0nz4I0** [HyperloopUPV-H8/ST-LIB#363]
idk what is happening, branch feature/test_BMSH works, development SPI  is not FIX ASAP,

:warning: 

https://github.com/HyperloopUPV-H8/ST-LIB/compare/feature/test_BMSH...development

**Comment by ricardochust** [comment]
if old spi works and new doesn t on a template project it is most probably the hal_msp and hal_it configuration, the DMA_spi changes of the template_project are needed on any project that wants to use the new spi.
