### ISSUE TITLE
Why main.c file name can't be changed and how to edit STM32CubeIDE templates to generate your own code

### ISSUE THREAD

**Issue by alejandrogonzalvo** [HyperloopUPV-H8/ST-LIB#42]
### Why main.c name can't be changed
When coding on C++, you need to change main.c file to main.cpp in order to compile everything. The problem is, you need to change it back to main.c in order to generate code.

Stm32CubeIDE is basically a bunch of plugins embedded into eclipse, and the code generator is one of those plugins. The name of the generated file is hardcoded into one of the java scripts, and since you download .class files you can't modify the behaviour of the generator because they are already compiled.

### How to generate your own code
What you can do on the other side, is modify the templates used to generate code. They are written in freemarker, and you can change them to generate whatever you want using the IOC and HAL data.

As an example, I have modified the main script to a minimalist version without all the bloated comments explaining everything.
[File Only available for hyperloop UPV members](https://drive.google.com/file/d/1RzgbaF08d6BI2PT_oCeWVTd23YprUIR6/view?usp=share_link)

Result:
![image](https://user-images.githubusercontent.com/59616818/202698431-fd1d4ef1-ce20-4938-b98b-d3dc872bcf28.png)

In order to use it, you need to paste it into this direction, and overwrite the existing file:
C:\ST\STM32CubeIDE_1.10.1\STM32CubeIDE\plugins\com.st.stm32cube.common.mx_6.6.1.202207061420\db\templates

For more information on code generation [check this user manual on stm32 code generation](https://www.st.com/resource/en/user_manual/dm00104712-stm32cubemx-for-stm32-configuration-and-initialization-c-code-generation-stmicroelectronics.pdf).

**Comment by PabloGonzalezSegarra** [comment]
These changes are very good but we postpone them until we have a stable version.
