### ISSUE TITLE
WARNING: adc3 has a cap of 12 bit resolution

### ISSUE THREAD

**Issue by ricardochust** [HyperloopUPV-H8/ST-LIB#43]
adc1 and adc2 can go up to 16 bit resolution (which is the resolution that we are asumming), but the adc3 on the H723ZG has its limit on 12 bits, it doesn t reach 16 bit resolution. 

if we are going to use the adc3 on any service, then we may need to take that into account. For example, the LookupSensor class assumes you have a 16 bit resolution to calculate the bit shift into the Lookup Table, which means it wouldn t work at all on the adc3, which gives a uint16_t variable but its value is only in the 12 bit range, so if it tries to fit 0000 1111 1111 1111 (which is the max value for adc3), it would get on a 256 lookup table 0000 1111 instead of 1111 1111 (as the class thinks that the range of values is 16 bit wide). 

So unless we are willing to reduce all resolutions to 12 bit, we will need to acknowledge the difference between adc1 and adc2 vs adc3 when writting code. I may need a method on the ADCs HALAL class to know wheter we work with 12 or 16 bits, otherwise the lookupSensors may not work on the adc3

**Comment by alejandrogonzalvo** [comment]
The ADC HALAL service already implements that distinction, and you receive a float value between 0 and 3.3 that represents the real value the adc gets. Then you can transform that value to an int of your desired resolution in order to work with lookuptables.
